version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 2
    groups:
      github-actions:
        patterns:
          - "*"
  - package-ecosystem: pip
    directory: /services/api
    schedule:
      interval: weekly
    open-pull-requests-limit: 2
    groups:
      python-minor-and-patch:
        patterns:
          - "*"
        update-types:
          - minor
          - patch
  - package-ecosystem: gradle
    directory: /apps/android
    schedule:
      interval: weekly
    open-pull-requests-limit: 2
    groups:
      android-minor-and-patch:
        patterns:
          - "*"
        update-types:
          - minor
          - patch
