[platformio]
default_envs = esp32dev

[env:esp32dev]
platform = espressif32@7.0.1
board = esp32dev
framework = espidf
monitor_speed = 115200
build_flags =
  -DROADSENSE_FIRMWARE_VERSION=\"0.1.0-dev\"
  -Wall
  -Wextra
  -Werror
